[news]
title = "미라클 어헤드 ─ Think Big 뉴스종합 ─ 전체"
url = "https://mirakle.mk.co.kr/list.php?sc=51800012"
entrySelector = "div.content_left div.list_area dl.article_list"
titleSelector = "dt.tit a"
linkSelector = "dt.tit a"
contentSelector = "dd.desc span.desctxt a"
imageSelector = "dd.thumb a img"
waitForSelector = "div.content_left div.list_area dl.article_list"
onFail = "stale"

[news_globalnow]
title = "미라클 어헤드 ─ Think Big 뉴스종합 ─ Global now"
url = "https://mirakle.mk.co.kr/list.php?sc=51800013"
entrySelector = "div.content_left div.list_area dl.article_list"
titleSelector = "dt.tit a"
linkSelector = "dt.tit a"
contentSelector = "dd.desc span.desctxt a"
imageSelector = "dd.thumb a img"
waitForSelector = "div.content_left div.list_area dl.article_list"
onFail = "stale"

[news_tech]
title = "미라클 어헤드 ─ Think Big 뉴스종합 ─ Tech"
url = "https://mirakle.mk.co.kr/list.php?sc=51800014"
entrySelector = "div.content_left div.list_area dl.article_list"
titleSelector = "dt.tit a"
linkSelector = "dt.tit a"
contentSelector = "dd.desc span.desctxt a"
imageSelector = "dd.thumb a img"
waitForSelector = "div.content_left div.list_area dl.article_list"
onFail = "stale"

[news_startup]
title = "미라클 어헤드 ─ Think Big 뉴스종합 ─ Startup"
url = "https://mirakle.mk.co.kr/list.php?sc=51800015"
entrySelector = "div.content_left div.list_area dl.article_list"
titleSelector = "dt.tit a"
linkSelector = "dt.tit a"
contentSelector = "dd.desc span.desctxt a"
imageSelector = "dd.thumb a img"
waitForSelector = "div.content_left div.list_area dl.article_list"
onFail = "stale"

[news_insights]
title = "미라클 어헤드 ─ Think Big 뉴스종합 ─ Insights"
url = "https://mirakle.mk.co.kr/list.php?sc=51800016"
entrySelector = "div.content_left div.list_area dl.article_list"
titleSelector = "dt.tit a"
linkSelector = "dt.tit a"
contentSelector = "dd.desc span.desctxt a"
imageSelector = "dd.thumb a img"
waitForSelector = "div.content_left div.list_area dl.article_list"
onFail = "stale"